language: node_js
sudo: false
node_js:
  - "12"
  - "10"
before_script:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.6.4.tgz
  - tar -zxvf mongodb-linux-x86_64-3.6.4.tgz
  - mkdir -p ./data/db/27017
  - mkdir -p ./data/db/27000
  - ./mongodb-linux-x86_64-3.6.4/bin/mongod --fork --nopreallocj --dbpath ./data/db/27017 --syslog --port 27017
notifications:
  email: false
